/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx,html,md}",
    "./src/app/html-files/**/*.{html,md}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#013220",
        "surface-dim": "#d9dad9",
        "on-tertiary-container": "#be8283",
        tertiary: "#2d0a0d",
        surface: "#f9f9f8",
        "on-surface": "#191c1c",
        secondary: "#735c00",
        "primary-fixed": "#bdedd2",
        "surface-variant": "#e1e3e2",
        "outline-variant": "#c1c8c2",
        outline: "#717973",
        "on-primary-fixed": "#002113",
        "on-tertiary-fixed": "#340f12",
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffe088",
        "tertiary-container": "#471e20",
        "tertiary-fixed-dim": "#f8b6b6",
        "on-error-container": "#93000a",
        "inverse-primary": "#a2d1b7",
        "on-error": "#ffffff",
        "surface-container-high": "#e7e8e7",
        "on-primary": "#ffffff",
        background: "#f9f9f8",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#241a00",
        "on-surface-variant": "#414943",
        error: "#ba1a1a",
        "surface-container": "#edeeed",
        "on-secondary-container": "#745c00",
        "tertiary-fixed": "#ffdad9",
        "surface-bright": "#f9f9f8",
        "inverse-on-surface": "#f0f1f0",
        "on-background": "#191c1c",
        "inverse-surface": "#2e3131",
        "secondary-fixed-dim": "#e9c349",
        "surface-container-low": "#f3f4f3",
        "on-primary-container": "#6f9c84",
        primary: "#001b0f",
        "surface-tint": "#3b6751",
        "on-tertiary-fixed-variant": "#68393b",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#574500",
        "surface-container-highest": "#e1e3e2",
        "secondary-container": "#fed65b",
        "on-primary-fixed-variant": "#234f3b",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#a2d1b7",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-instrument)", "serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
        serif: ["var(--font-instrument)", "serif"],
        sans: ["var(--font-inter)", "sans-serif"],
      },
      boxShadow: {
        ambient: "0 40px 60px -20px rgba(25, 28, 28, 0.08)",
      },
      keyframes: {
        scroll: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      animation: {
        "impact-scroll": "scroll 40s linear infinite",
      },
    },
  },
  plugins: [],
};
